# Required environment variables:
# KCPP_MODEL_FILE=model.gguf
# KCPP_MODELS_PATH=<path to your models directory>

# Optional environment variables:
# KCPP_PORT=5001
# KCPP_GPU_SELECTION=all,0,1,etc.

# KoboldCPP pasrameters:
# KCPP_TENSOR_SPLIT= '1 1' for dual gpu, '1' for single gpu
# KCPP_CONTEXT_SIZE=32768
# KCPP_CONTEXT_SIZE=65536
# KCPP_CONTEXT_SIZE=131072
# KCPP_QUANTKV=2
# KCPP_GPULAYERS=999
# KCPP_THREADS=12
# KCPP_BATCHSIZE=256
# KCPP_MAXREQUESTSIZE=64
# KCPP_DEFAULTGENAMT=2048

# These work as switches. If the var has any content, including "0" or "false", the flag will be added. If the var is empty or not set, the flag will be omitted.
# KCPP_USECUDA=1
# KCPP_SMARTCONTEXT=1
# KCPP_JINJA=1
# KCPP_JINJA_TOOLS=1
# KCPP_LOWVRAM=1
# KCPP_NOFLASHATTENTION=1


version: "3.9"

services:
  koboldcpp:
    image: ghcr.io/dam-pav/koboldcpp:latest
    container_name: koboldcpp
    environment:
      KCPP_MODEL: "/app/models/${KCPP_MODEL_FILE}"
      KCPP_ARGS: >-
        --tensor_split ${KCPP_TENSOR_SPLIT:-1 1}
        --contextsize ${KCPP_CONTEXT_SIZE:-32768}
        --quantkv ${KCPP_QUANTKV:-2}
        --gpulayers ${KCPP_GPULAYERS:-999}
        --threads ${KCPP_THREADS:-12}
        --batchsize ${KCPP_BATCHSIZE:-256}
        --maxrequestsize ${KCPP_MAXREQUESTSIZE:-64}
        --defaultgenamt ${KCPP_DEFAULTGENAMT:-2048}
        $${KCPP_USECUDA:+--usecuda}
        $${KCPP_SMARTCONTEXT:+--smartcontext}
        $${KCPP_JINJA:+--jinja}
        $${KCPP_JINJA_TOOLS:+--jinja_tools}
        $${KCPP_LOWVRAM:+--lowvram}
        $${KCPP_NOFLASHATTENTION:+--noflashattention}

      KCPP_HOST: "0.0.0.0"
      KCPP_PORT: "5001"

      NVIDIA_VISIBLE_DEVICES: "${KCPP_GPU_SELECTION:-all}"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"

    volumes:
      - ${KCPP_MODELS_PATH}:/app/models
    ports:
      - "${KCPP_PORT:-5001}:5001"

    # For Docker 29 compose (non-swarm), this is the important bit:
    gpus:
      - device_ids: ["${KCPP_GPU_SELECTION:-all}"]
        capabilities: ["gpu"]
        
    restart: unless-stopped
